# Generated by Django 4.1.3 on 2022-11-30 22:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storetype',
            name='refrigerant',
        ),
        migrations.AddField(
            model_name='store',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.region'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.storetype'),
        ),
        migrations.AddField(
            model_name='store',
            name='subcontractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.subcontractor'),
        ),
        migrations.AddField(
            model_name='store',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.supervisor'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
