# Generated by Django 4.1.3 on 2022-11-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_storetype_refrigerant_store_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractor',
            name='phone_number',
            field=models.CharField(max_length=9),
        ),
    ]
