# Generated by Django 4.1.3 on 2022-12-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_store_date_disassembling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_number',
            field=models.CharField(max_length=4),
        ),
    ]
