# Generated by Django 4.1.3 on 2023-01-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_store_store_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
