# Generated by Django 4.1.3 on 2023-01-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_number', models.CharField(max_length=4)),
                ('store_city', models.CharField(max_length=30)),
                ('store_street', models.CharField(max_length=30)),
                ('store_street_number', models.IntegerField()),
                ('zip_code', models.CharField(max_length=6)),
                ('date_start_installation', models.DateTimeField()),
                ('date_opening', models.DateTimeField()),
                ('date_disassembling', models.DateTimeField(null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.region')),
                ('store_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.storetype')),
                ('subcontractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.subcontractor')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.supervisor')),
            ],
        ),
    ]
